#!/usr/bin/env bash
set -euo pipefail
#######################################################################
# MutateX Utility Functions
#
# Common functions for MutateX batch processing.
# Source this file in your scripts:
#   source "$SCRIPT_DIR/modules/PPI/mutatex_utils.sh"
#######################################################################

# Background cleanup function - runs during mutatex to keep disk usage low
# Only removes files from mutation directories that are CONFIRMED complete
# (i.e. they already contain an Average_*.fxout summary file).
# Average_*.fxout, Dif_*.fxout, and selfmutation_energies*.dat are NEVER deleted
# because they are required for visualization and critical-residue extraction.
# Usage: cleanup_worker <mutations_dir> [interval_seconds]
# Returns: PID of background process (use to kill later)
cleanup_worker() {
    local mutations_dir="$1"
    local interval="${2:-60}"  # Check every 60 seconds
    
    while true; do
        sleep "$interval"
        if [[ -d "$mutations_dir" ]]; then
            # Remove PDB files from completed mutation directories (those with Average_*.fxout)
            find "$mutations_dir" -type d -mindepth 2 -maxdepth 2 | while IFS= read -r mutdir; do
                if ls "$mutdir"/Average_*.fxout 1>/dev/null 2>&1; then
                    # Mutation completed, safe to delete PDBs
                    find "$mutdir" -type f -name "*.pdb" -delete 2>/dev/null
                    rm -rf "$mutdir/molecules" 2>/dev/null
                fi
            done
        fi
    done
}

# Post-run cleanup function - aggressive cleanup after mutatex completes
# Deletes transient files (*.pdb, Raw_*.fxout, PdbList_*.fxout, molecules/)
# but PRESERVES all files needed by visualization & extraction:
#   - Average_*.fxout   (summary ΔΔG per mutation)
#   - Dif_*.fxout       (difference energies)
#   - selfmutation_energies*.dat
#   - results/, results_selfmutation/, pymol_visualization/, visualizations/
# Usage: cleanup_mutations_dir <mutations_dir>
cleanup_mutations_dir() {
    local mutations_dir="$1"
    
    if [[ ! -d "$mutations_dir" ]]; then
        return 0
    fi
    
    # Delete all PDB files in mutation subdirectories (both mutant and WT structures)
    # These are regenerated per mutation and consume ~280MB × number_of_mutations
    find "$mutations_dir" -type f -name "*.pdb" -delete
    
    # Delete raw FoldX output files — keep Average_* and Dif_* summaries
    find "$mutations_dir" -type f \( \
        -name "Raw_*.fxout" \
        -o -name "PdbList_*.fxout" \
    \) -delete
    
    # Delete molecules subdirectories (temporary FoldX files)
    find "$mutations_dir" -type d -name "molecules" -exec rm -rf {} + 2>/dev/null || true
}

# Start cleanup worker in background and return PID
# Usage: start_cleanup_worker <mutations_dir> [interval]
#        cleanup_pid=$(start_cleanup_worker "$outdir/mutations" 30)
start_cleanup_worker() {
    local mutations_dir="$1"
    local interval="${2:-60}"
    
    # Redirect stdout/stderr so the background process does not hold
    # the $() command-substitution pipe open (which would hang the caller).
    cleanup_worker "$mutations_dir" "$interval" >/dev/null 2>&1 &
    echo "$!"
}

# Stop cleanup worker by PID
# Usage: stop_cleanup_worker $cleanup_pid
stop_cleanup_worker() {
    local pid="$1"
    
    if [[ -n "$pid" ]]; then
        kill "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
    fi
}

#######################################################################
# PyMOL Visualization Generation
# Uses ddg2pdb to create PyMOL-compatible visualizations with DDG data
# mapped to B-factors for heatmap coloring of critical interface residues
#######################################################################

# Generate mutation_list.txt file (default 20 amino acids)
# Usage: create_mutation_list <output_dir>
create_mutation_list() {
    local output_dir="$1"
    local mutlist_file="$output_dir/mutation_list.txt"
    
    if [[ ! -f "$mutlist_file" ]]; then
        cat > "$mutlist_file" << 'EOF'
G
A
V
L
I
M
F
W
P
S
T
C
Y
N
Q
D
E
K
R
H
EOF
        echo "[INFO] Created mutation_list.txt at $mutlist_file"
    fi
    echo "$mutlist_file"
}

# Generate PyMOL visualization script
# Usage: create_pymol_script <output_dir> <pdb_basename>
create_pymol_script() {
    local output_dir="$1"
    local pdb_basename="$2"
    local pymol_dir="$output_dir/pymol_visualization"
    local pml_file="$pymol_dir/visualize_ddg_heatmap.pml"
    
    mkdir -p "$pymol_dir"
    
    cat > "$pml_file" << 'PYMOL_SCRIPT'
# MutateX DDG Heatmap Visualization Script for PyMOL
# Generated by mutatex_repo_version.sh
#
# Usage: Open PyMOL and run: @visualize_ddg_heatmap.pml
# Or: pymol visualize_ddg_heatmap.pml
#
# This script loads PDB files with DDG data in B-factor fields
# and colors residues by mutation sensitivity (destabilizing = red, stabilizing = blue)

# Reinitialize and set up visualization
reinitialize
bg_color white
set ray_opaque_background, on
set antialias, 2
set cartoon_fancy_helices, 1
set cartoon_side_chain_helper, on

# Load the interface DDG PDB files
# Destabilizing mutations (DDG > 0.5 kcal/mol)
PYMOL_SCRIPT

    # Add commands to load the generated PDB files
    cat >> "$pml_file" << PYMOL_LOAD
# Load interface PDB files with DDG data
python
import os
import glob

# Find all interface DDG PDB files
pdb_dir = os.path.dirname(os.path.abspath("$pml_file"))
interface_pdbs = glob.glob(os.path.join(pdb_dir, "*_interface_ddg_*.pdb"))
folding_pdbs = glob.glob(os.path.join(pdb_dir, "*_folding_ddg_*.pdb"))

# Load interface PDG files
for i, pdb in enumerate(sorted(interface_pdbs)):
    obj_name = os.path.basename(pdb).replace('.pdb', '')
    cmd.load(pdb, obj_name)
    print(f"Loaded: {obj_name}")

# Load folding PDB files if present
for i, pdb in enumerate(sorted(folding_pdbs)):
    obj_name = os.path.basename(pdb).replace('.pdb', '')
    cmd.load(pdb, obj_name)
    print(f"Loaded: {obj_name}")
python end
PYMOL_LOAD

    cat >> "$pml_file" << 'PYMOL_COLORS'

# Create custom color spectrum for DDG values
# Blue = stabilizing (negative DDG), White = neutral, Red = destabilizing (positive DDG)
set_color ddg_blue, [0.2, 0.4, 0.8]
set_color ddg_red, [0.9, 0.2, 0.2]

# Apply B-factor coloring to all loaded structures
# The B-factor contains the count of mutations above/below thresholds
python
for obj in cmd.get_object_list():
    # Show as cartoon with surface
    cmd.show("cartoon", obj)
    cmd.show("surface", obj)
    cmd.set("surface_color", "white", obj)
    cmd.set("transparency", 0.7, obj)
    
    # Color by B-factor (DDG count values)
    cmd.spectrum("b", "blue_white_red", obj, minimum=0, maximum=10)
    
    # Highlight high-impact residues
    cmd.select("hotspots_" + obj, f"{obj} and b > 5")
    cmd.show("sticks", "hotspots_" + obj)
    
print("Applied DDG heatmap coloring to all structures")
python end

# Set up nice viewing parameters
set cartoon_transparency, 0.0
set stick_radius, 0.15
set sphere_scale, 0.2

# Add labels to hotspot residues
python
for obj in cmd.get_object_list():
    if "interface" in obj.lower():
        # Label interface hotspots
        cmd.label(f"hotspots_{obj} and name CA", '"%.0f" % b')
python end

# Orient view
orient
zoom

# Create scenes for easy navigation
scene interface_overview, store
disable all
python
for obj in cmd.get_object_list():
    if "interface" in obj.lower():
        cmd.enable(obj)
python end
scene interface_only, store

disable all
python
for obj in cmd.get_object_list():
    if "folding" in obj.lower():
        cmd.enable(obj)
python end
scene folding_only, store

enable all
scene all_data, store

# Print instructions
print("")
print("=" * 60)
print("MutateX DDG Heatmap Visualization Loaded")
print("=" * 60)
print("")
print("Color interpretation:")
print("  BLUE = Stabilizing mutations (negative DDG)")  
print("  WHITE = Neutral")
print("  RED = Destabilizing mutations (positive DDG)")
print("")
print("The B-factor value shows the count of mutations")
print("above the destabilizing threshold (0.5 kcal/mol)")
print("")
print("Scenes available:")
print("  scene interface_overview  - All structures")
print("  scene interface_only      - Interface DDG only")
print("  scene folding_only        - Folding DDG only")
print("")
print("Hotspot residues (high mutation sensitivity) are")
print("shown as sticks with labels.")
print("=" * 60)
PYMOL_COLORS

    echo "[INFO] Created PyMOL script: $pml_file"
    echo "$pml_file"
}

# Main function to generate PyMOL visualization
# Usage: generate_pymol_visualization <results_dir> <pdb_basename>
generate_pymol_visualization() {
    local results_dir="$1"
    local pdb_basename="$2"
    local pymol_dir="$results_dir/pymol_visualization"
    
    mkdir -p "$pymol_dir"
    
    # Find the repaired PDB file
    local repaired_pdb=""
    repaired_pdb=$(find "$results_dir" -name "*_model0_checked.pdb" -o -name "*_Repair.pdb" 2>/dev/null | head -1)
    
    if [[ -z "$repaired_pdb" ]]; then
        repaired_pdb=$(find "$results_dir" -name "*.pdb" 2>/dev/null | head -1)
    fi
    
    if [[ -z "$repaired_pdb" ]]; then
        echo "[WARNING] No PDB file found in $results_dir"
        return 1
    fi
    
    # Create mutation list file using shared function
    local mutlist_file
    mutlist_file=$(create_mutation_list "$results_dir")
    
    # Find interface DDG directories
    local interface_base="$results_dir/results/interface_ddgs/final_averages"
    local mutation_base="$results_dir/results/mutation_ddgs"
    
    # Generate PyMOL PDB files for interface DDGs
    if [[ -d "$interface_base" ]]; then
        for ddg_dir in "$interface_base"/*/; do
            [[ -d "$ddg_dir" ]] || continue
            local chain_pair="${ddg_dir%/}"; chain_pair="${chain_pair##*/}"
            if true; then
                local out_pdb="$pymol_dir/${pdb_basename}_interface_ddg_${chain_pair}.pdb"
                local out_matrix="$pymol_dir/${pdb_basename}_interface_ddg_${chain_pair}_matrix.dat"
                
                echo "[INFO] Generating interface DDG visualization for chain pair $chain_pair..."
                
                # Generate PDB with destabilizing mutations (DDG > 0.5)
                ddg2pdb \
                    -p "$repaired_pdb" \
                    -d "$ddg_dir" \
                    -l "$mutlist_file" \
                    -b 0.5 \
                    -o "$out_pdb" \
                    -m "$out_matrix" \
                    -v 2>&1 || echo "[WARNING] ddg2pdb failed for $chain_pair"
                
                if [[ -f "$out_pdb" ]]; then
                    echo "[INFO] Created: $out_pdb"
                fi
            fi
        done
    else
        echo "[INFO] No interface DDG results found at $interface_base"
    fi
    
    # Generate PyMOL PDB files for folding/mutation DDGs
    local folding_dir=""
    if [[ -d "$mutation_base" ]]; then
        folding_dir=$(find "$mutation_base" -type d -name "*_Repair" 2>/dev/null | head -1)
    fi
    
    if [[ -d "$folding_dir" ]]; then
        local out_pdb="$pymol_dir/${pdb_basename}_folding_ddg.pdb"
        local out_matrix="$pymol_dir/${pdb_basename}_folding_ddg_matrix.dat"
        
        echo "[INFO] Generating folding DDG visualization..."
        
        ddg2pdb \
            -p "$repaired_pdb" \
            -d "$folding_dir" \
            -l "$mutlist_file" \
            -b 0.5 \
            -o "$out_pdb" \
            -m "$out_matrix" \
            -v 2>&1 || echo "[WARNING] ddg2pdb failed for folding DDG"
        
        if [[ -f "$out_pdb" ]]; then
            echo "[INFO] Created: $out_pdb"
        fi
    else
        echo "[INFO] No folding DDG results found at $mutation_base"
    fi
    
    # Create PyMOL visualization script
    create_pymol_script "$results_dir" "$pdb_basename"
    
    # Create README for visualization
    cat > "$pymol_dir/README.txt" << README
MutateX PyMOL Visualization
============================

This directory contains PyMOL-compatible visualization files for the
MutateX saturation mutagenesis results.

Files:
------
- *_interface_ddg_*.pdb : PDB files with interface DDG data in B-factors
- *_folding_ddg.pdb     : PDB file with folding DDG data in B-factors  
- *_matrix.dat          : xPyder-compatible matrix files
- visualize_ddg_heatmap.pml : PyMOL script for visualization

Usage:
------
1. Open PyMOL
2. Navigate to this directory
3. Run: @visualize_ddg_heatmap.pml

Or from command line:
  pymol visualize_ddg_heatmap.pml

Interpretation:
--------------
The B-factor field contains the count of mutations at each position
that exceed the destabilizing threshold (0.5 kcal/mol).

- Higher B-factor = More mutations are destabilizing = Critical residue
- BLUE coloring = Stabilizing mutations dominate
- RED coloring = Destabilizing mutations dominate

Interface hotspots are residues where many mutations disrupt binding.
These are likely critical for the protein-protein interaction.

xPyder Plugin:
--------------
For more advanced visualization, use the xPyder PyMOL plugin with
the *_matrix.dat files. See: https://github.com/ELELAB/xPyder

Generated: $(printf '%(%Y-%m-%d %H:%M:%S %Z)T' -1)
README

    echo "[INFO] PyMOL visualization files saved to: $pymol_dir"
    return 0
}
